<?php
define('DB_HOST', '127.0.0.1');
define('DB_USER', 'root');
define('DB_PASSWORD', '');
define('DB_NAME', '20%project');

define('SCHOOL_ADMIN_AUTHENTICATED', '1');
define('SCHOOL_ADMIN_AUTHENTICATION_FAILED', '2');

define('SCHOOL_CREATED', '3');
define('SCHOOL_CREATION_FAILED', '4');
define('SCHOOL_EXISTS', '5');
define('SCHOOL_UPDATED', '6');
define('SCHOOL_UPDATE_FAILED', '7');
define('SCHOOL_DELETED', '8');
define('SCHOOL_DELETION_FAILED', '9');

define('STUDENT_CREATED', '10');
define('STUDENT_CREATE_FAILED', '11');
define('STUDENT_EXISTS', '12');
define('STUDENT_UPDATED', '103');
define('STUDENT_UPDATE_FAILED', '14');
define('STUDENT_DELETED', '15');
define('STUDENT_DELETION_FAILED', '16');

define('USERS_CREATED', '17');
define('USERS_CREATE_FAILED', '18');
define('USERS_EXISTS', '19');
define('USERS_UPDATED', '20');
define('USERS_UPDATE_FAILED', '21');
define('USERS_DELETED', '22');
define('USERS_DELETION_FAILED', '23');

define('CLASS_CREATED', '24');
define('CLASS_CREATE_FAILED', '25');
define('CLASS_EXISTS', '26');
define('CLASS_UPDATED', '27');
define('CLASS_UPDATE_FAILED', '28');
define('CLASS_DELETED', '29');
define('CLASS_DELETION_FAILED', '30');

define('PROJECTMARKS_CREATED', '31');
define('PROJECTMARKS_CREATE_FAILED', '32');
define('PROJECTMARKS_EXISTS', '33');
define('PROJECTMARKS_UPDATED', '34');
define('PROJECTMARKS_UPDATE_FAILED', '35');
define('PROJECTMARKS_DELETED', '36');
define('PROJECTMARKS_DELETION_FAILED', '37');

define('PROJECTDETAILS_CREATED', '38');
define('PROJECTDETAILS_CREATE_FAILED', '39');
define('PROJECTDETAILSY_EXISTS', '40');
define('PROJECTDETAILS_UPDATED', '41');
define('PROJECTDETAILS_UPDATE_FAILED', '42');
define('PROJECTDETAILS_DELETED', '43');
define('PROJECTDETAILS_DELETION_FAILED', '44');

define('PROJECTTYPE_CREATED', '45');
define('PROJECTTYPE_CREATE_FAILED', '46');
define('PROJECTTYPE_EXISTS', '47');
define('PROJECTTYPE_UPDATED', '48');
define('PROJECTTYPE_UPDATE_FAILED', '49');
define('PROJECTTYPE_DELETED', '50');
define('PROJECTTYPE_DELETION_FAILED', '51');

define('PROJECT_CREATED', '52');
define('PROJECT_CREATION_FAILED', '53');
define('PROJECT_EXISTS', '54');
define('PROJECT_UPDATED', '55');
define('PROJECT_UPDATE_FAILED', '56');
define('PROJECT_DELETED', '57');
define('PROJECT_DELETION_FAILED', '58');

define('RESULT_CREATED', '59');
define('RESULT_CREATE_FAILED', '60');
define('RESULT_EXISTS', '61');
define('RESULT_UPDATED', '62');
define('RESULT_UPDATE_FAILED', '63');
define('RESULT_DELETED', '64');
define('RESULT_DELETION_FAILED', '65');

define('SUBJECT_CREATED', '500');
define('SUBJECT_CREATION_FAILED', '501');
define('SUBJECT_EXITS', '502');
define('SUBJECT_DELETED', '503');
define('SUBJECT_DELETION_FAILED', '504');
define('SUBJECT_UPDATED', '505');
define('SUBJECT_UPDATE_FAILED', '506');

define('STRING', '66');
define('INTEGER', '67');
define('BOOLEAN', '68');
